version: '3.5'

services:

  testrunner:
    image: "${TAG}"
    depends_on:
      - mongodb
    environment:
      - SOPI_TESTS_MONGODB__PORT=27017
      - SOPI_TESTS_MONGODB__DATABASEID=testrun
      - SOPI_TESTS_MONGODB__SERVER=mongodb
    volumes:
      - "${TESTRESULTS}:/testresults"
    command: ["dotnet", "test", "--logger:trx", "--no-build", "--no-restore", "-c", "${CONFIGURATION}", "-r" , "/testresults" , "/p:NuGetVersionV2=${NUGETVERSIONV2}", "/p:AssemblySemVer=${ASSEMBLYSEMVER}" ]