version: '3.5'

services:

  testrunner:
    image: "${TAG}"
    depends_on:
      - mongodb
    environment:
      - SOPI_TESTS_MONGODB__PORT=27017
      - SOPI_TESTS_MONGODB__DATABASEID=testrun
      - SOPI_TESTS_MONGODB__SERVER=mongodb
    volumes:
      - "${TESTRESULTS}:/testresults"